"use client";

import { useMemo, useState } from "react";
import type { ChartPoint, Evaluation, RunTelemetry } from "@/lib/telemetry";
import { maximumStressedDrawdown, stressImpact } from "@/lib/presentation-metrics";
import { runContext } from "@/lib/run-context";
import { replayViews, type ReplayView } from "@/lib/replay-navigation";
import { defaultVerifiedRun, verifiedRuns, type VerifiedRun, type VerifiedRunId } from "@/lib/verified-runs";

const money = new Intl.NumberFormat("en-AU", { style: "percent", minimumFractionDigits: 2, maximumFractionDigits: 2 });
const dateFormat = new Intl.DateTimeFormat("en-AU", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" });

function formatDate(date: string): string { return dateFormat.format(new Date(`${date}T00:00:00Z`)); }
function shock(evaluation: Evaluation, symbol: string): number { return evaluation.scenario.components[0]?.shocks?.[symbol] ?? 0; }
function defender(run: RunTelemetry, evaluation: Evaluation) { return run.defenderVerdicts.find((item) => item.scenarioId === evaluation.result.scenarioId); }
function path(points: readonly ChartPoint[], value: (point: ChartPoint) => number, min: number, max: number, height: number): string {
  return points.map((point, index) => `${index === 0 ? "M" : "L"}${(index / Math.max(points.length - 1, 1)) * 1000},${height - ((value(point) - min) / Math.max(max - min, 0.0001)) * height}`).join(" ");
}

function EquityChart({ evaluation, mode }: { evaluation: Evaluation; mode: "equity" | "drawdown" }) {
  const [active, setActive] = useState<number | null>(null);
  const points = evaluation.chartPoints;
  const stressDate = evaluation.scenario.components.find((item) => item.date)?.date;
  const stressIndex = points.findIndex((point) => point.date === stressDate);
  const values = mode === "equity" ? points.flatMap((point) => [point.baselineEquity, point.stressedEquity]) : points.map((point) => -point.stressedDrawdown);
  const min = mode === "equity" ? Math.min(...values) * 0.985 : Math.min(...values) * 1.08;
  const max = mode === "equity" ? Math.max(...values) * 1.01 : 0;
  const activePoint = active === null ? null : points[active];
  const markerX = Math.max(stressIndex, 0) / Math.max(points.length - 1, 1) * 1000;
  const selectPoint = (clientX: number, bounds: DOMRect) => setActive(Math.round(Math.max(0, Math.min(1, (clientX - bounds.left) / bounds.width)) * (points.length - 1)));

  return <div className="chart-wrap">
    <svg viewBox="0 0 1000 390" role="img" aria-label={mode === "equity" ? "Normalized portfolio equity chart" : "Stressed portfolio drawdown chart"} tabIndex={0}
      onPointerMove={(event) => selectPoint(event.clientX, event.currentTarget.getBoundingClientRect())}
      onPointerLeave={() => setActive(null)}
      onKeyDown={(event) => { if (event.key === "ArrowRight") { event.preventDefault(); setActive((active ?? 0) < points.length - 1 ? (active ?? 0) + 1 : points.length - 1); } if (event.key === "ArrowLeft") { event.preventDefault(); setActive((active ?? points.length - 1) > 0 ? (active ?? points.length - 1) - 1 : 0); } }}>
      {[0, .25, .5, .75, 1].map((ratio) => <g key={ratio}><line className="grid" x1="0" x2="1000" y1={35 + ratio * 310} y2={35 + ratio * 310} /><text className="axis-label" x="-4" y={39 + ratio * 310} textAnchor="end">{mode === "equity" ? (max - (max - min) * ratio).toFixed(2) : money.format(max - (max - min) * ratio)}</text></g>)}
      {mode === "equity" && <><path className="line baseline-line" d={path(points, (point) => point.baselineEquity, min, max, 310)} transform="translate(0 35)" /><path className="line stressed-line" d={path(points, (point) => point.stressedEquity, min, max, 310)} transform="translate(0 35)" /></>}
      {mode === "drawdown" && <><path className="drawdown-area" d={`${path(points, (point) => -point.stressedDrawdown, min, max, 310)} L1000,35 L0,35 Z`} transform="translate(0 35)" /><path className="line drawdown-line" d={path(points, (point) => -point.stressedDrawdown, min, max, 310)} transform="translate(0 35)" /></>}
      <g className="attack-marker"><line x1={markerX} x2={markerX} y1="25" y2="350" /><text x={Math.min(markerX + 8, 865)} y="22">Selected stress · {stressDate ? formatDate(stressDate) : "—"}</text></g>
      {activePoint && <g className="active-point"><line x1={(active! / (points.length - 1)) * 1000} x2={(active! / (points.length - 1)) * 1000} y1="35" y2="345" /><circle cx={(active! / (points.length - 1)) * 1000} cy={35 + 310 - ((mode === "equity" ? activePoint.stressedEquity : -activePoint.stressedDrawdown) - min) / (max - min) * 310} r="4" /></g>}
      <text className="axis-label" x="0" y="382">{formatDate(points[0]?.date ?? "2024-01-02")}</text><text className="axis-label" x="1000" y="382" textAnchor="end">{formatDate(points.at(-1)?.date ?? "2024-04-23")}</text>
    </svg>
    {activePoint && <aside className="chart-tooltip" aria-live="polite"><strong>{formatDate(activePoint.date)}</strong><span>Baseline <b>{activePoint.baselineEquity.toFixed(4)}</b></span><span>Stressed <b>{activePoint.stressedEquity.toFixed(4)}</b></span><span>Difference <b>{money.format(activePoint.stressedEquity / activePoint.baselineEquity - 1)}</b></span><span>Stressed drawdown <b>{money.format(activePoint.stressedDrawdown)}</b></span></aside>}
  </div>;
}

function Overview({ selected, onSelect }: { selected: VerifiedRun; onSelect: (id: VerifiedRunId) => void }) {
  const { run, evaluation } = selected; const replay = defender(run, evaluation); const impact = stressImpact(evaluation); const drawdown = maximumStressedDrawdown(evaluation); const date = evaluation.scenario.components[0]?.date ?? "";
  const context = runContext(selected.id, run.configSha256);
  const [mode, setMode] = useState<"equity" | "drawdown">("equity");
  return <>
    <section className="run-context" aria-labelledby="context-title"><div><p className="section-kicker">Run context</p><h2 id="context-title">Monthly 60/40 stress evaluation</h2></div><dl><div><dt>Strategy</dt><dd>{context.strategy}</dd></div><div><dt>Rebalancing</dt><dd>{context.rebalancing}</dd></div><div><dt>Period</dt><dd>{context.period}</dd></div><div><dt>Starting value</dt><dd>{context.startingValue}</dd></div><div><dt>Model role</dt><dd>{context.modelRole}</dd></div></dl><p className="context-proof">Context record v{context.schemaVersion} is tied to this run’s recorded config hash.</p></section>
    <section className="result-row" aria-label="Primary result metrics"><div><span>Recorded risk events</span><strong>{evaluation.result.breachCount ?? "—"}</strong></div><div><span>Stressed max drawdown</span><strong>{money.format(drawdown)}</strong></div><div><span>Immediate stress impact</span><strong className="stress-value">{money.format(impact)}</strong></div><div><span>Verification</span><strong className="verified-value">Reproduced <small>Δ {replay?.maxMetricDelta.toFixed(1) ?? "—"}</small></strong></div></section>
    <section className="explorer" aria-label="Verified scenario explorer"><div><label htmlFor="scenario">Explore verified stress</label><select id="scenario" value={selected.id} onChange={(event) => onSelect(event.target.value as VerifiedRunId)}>{verifiedRuns.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><small>Precomputed verified scenarios — no live model call.</small></div><p><b>{selected.label}</b><span>{selected.id === defaultVerifiedRun.id ? "Default replay" : "Alternate replay"} · {evaluation.result.scenarioId}</span></p></section>
    <section className="analysis-grid"><section className="chart-panel"><header className="chart-header"><div><p className="section-kicker">Portfolio path</p><h2>{mode === "equity" ? "Normalized portfolio equity" : "Stressed portfolio drawdown"}</h2><p>{mode === "equity" ? "1.00 = starting portfolio value" : "Drawdown = decline from the portfolio’s previous peak."}</p></div><div className="segment" aria-label="Chart type"><button className={mode === "equity" ? "active" : ""} onClick={() => setMode("equity")}>Equity</button><button className={mode === "drawdown" ? "active" : ""} onClick={() => setMode("drawdown")}>Drawdown</button></div></header><div className="chart-legend" aria-label="Chart legend">{mode === "equity" ? <><span className="baseline-key" />Baseline <span className="stressed-key" />Stressed</> : <><span className="drawdown-key" />Stressed drawdown below zero</>}<span className="attack-key" />Stress marker</div><EquityChart evaluation={evaluation} mode={mode} /></section><aside className="stress-panel"><p className="section-kicker">Selected stress</p><h2>One-day gap</h2><time>{formatDate(date)}</time><dl><div><dt>SPY</dt><dd>{money.format(shock(evaluation, "SPY"))}</dd></div><div><dt>TLT</dt><dd>{money.format(shock(evaluation, "TLT"))}</dd></div><div><dt>Portfolio impact</dt><dd>{money.format(impact)}</dd></div></dl><p>Selected by Ollama from a prevalidated catalog. Numerical values and portfolio calculations are owned by Python.</p></aside></section>
    <section className="explanation"><div><p className="section-kicker">What happened?</p><h2>Verified impact, not a forecast</h2><p>On {formatDate(date)}, the selected one-day gap stress reduced the portfolio by approximately {money.format(Math.abs(impact))} relative to its unstressed path. The stressed portfolio recorded {evaluation.result.breachCount} risk-limit events and reached a maximum drawdown of {money.format(drawdown)}.</p><small>Independent replay reproduced the deterministic result with a metric delta of {replay?.maxMetricDelta.toFixed(1) ?? "—"}. This is research evidence, not investment advice.</small></div><div className="chart-guide"><h3>How to read this chart</h3><dl><div><dt>Baseline</dt><dd>Portfolio path without the selected attack.</dd></div><div><dt>Stressed</dt><dd>Same deterministic strategy with the stress applied.</dd></div><div><dt>1.00</dt><dd>Starting normalized portfolio value.</dd></div><div><dt>Stress marker</dt><dd>The artificial scenario date, not an inferred breach date.</dd></div></dl></div></section>
  </>;
}

function Method() { return <section className="method-view"><header><p className="section-kicker">Method</p><h2>Bounded AI selection, deterministic evaluation</h2><p>Every scenario begins as an admissible catalog key; numerical evidence stays with the Python engine.</p></header><div className="method-stages"><article><span>01</span><h3>Select</h3><p>Ollama chooses a key from a finite prevalidated AttackCatalog.</p></article><article><span>02</span><h3>Calculate</h3><p>Deterministic Python owns dates, numerical shocks, portfolio simulation and risk metrics.</p></article><article><span>03</span><h3>Verify</h3><p>The defender independently reruns selected failures and compares numerical results.</p></article></div><p className="method-close">LLM selects. Python calculates. Defender verifies.</p><small>The model never supplies executable code or numerical market parameters directly to the engine.</small></section>; }
function Evidence({ selected }: { selected: VerifiedRun }) { const { run, evaluation } = selected; const replay = defender(run, evaluation); return <section className="evidence-view"><header><p className="section-kicker">Evidence</p><h2>Recorded telemetry and release provenance</h2><p>Technical evidence is preserved for this selected, independently reproduced replay.</p></header><dl className="evidence-metrics"><div><dt>Scenario ID</dt><dd><code>{evaluation.result.scenarioId}</code></dd></div><div><dt>Provider / model</dt><dd>{run.provider} / {run.modelIdentifier}</dd></div><div><dt>Maximum normalized excess</dt><dd>{evaluation.result.maximumNormalizedExcess}</dd></div><div><dt>Chart point count</dt><dd>{evaluation.chartPoints.length}</dd></div><div><dt>Breach event count</dt><dd>{evaluation.result.breachCount}</dd></div><div><dt>Defender replay delta</dt><dd>{replay?.maxMetricDelta ?? "—"}</dd></div><div><dt>Verification verdict</dt><dd className="verified-value">{replay?.verdict ?? run.verificationVerdict}</dd></div><div><dt>Fixture provenance</dt><dd><code>{selected.id === "run-024" ? "ollama-run-024" : "ollama-run-025"}</code></dd></div></dl><section className="hash-grid"><div><span>Data SHA256</span><code>{run.dataSha256}</code></div><div><span>Config SHA256</span><code>{run.configSha256}</code></div></section><section className="timeline"><h3>Canonical event timeline</h3><ol>{run.events.map((event) => <li key={event.sequence}><span>{String(event.sequence).padStart(2, "0")}</span><div><b>{event.eventType.replaceAll("_", " ")}</b><small>{event.scenarioId ?? "run"}{event.roundNumber ? ` · round ${event.roundNumber}` : ""}</small></div></li>)}</ol></section><p className="research-note">Research-only replay. Vercel serves static evidence; it runs no Python backend, Ollama service, or model credentials.</p></section>; }

export function ReplayDashboard() { const [view, setView] = useState<ReplayView>("overview"); const [selectedId, setSelectedId] = useState(defaultVerifiedRun.id); const selected = useMemo(() => verifiedRuns.find((item) => item.id === selectedId) ?? defaultVerifiedRun, [selectedId]); return <main><header className="product-header"><div><div className="title-line"><h1>Trading Strategy Red-Team Lab</h1><span className="verified-badge">● Verified</span></div><h2>Can a 60/40 portfolio survive adversarial market shocks?</h2><p>AI selects a prevalidated stress scenario. Deterministic Python evaluates the portfolio. An independent replay verifies the result.</p></div><a href="https://github.com/cx07-oss/strategy-redteam-lab" target="_blank" rel="noreferrer">View source ↗</a></header><nav className="tabs" aria-label="Replay sections">{replayViews.map(({ id, label }) => <button key={id} className={view === id ? "active" : ""} onClick={() => setView(id)}>{label}</button>)}</nav>{view === "overview" && <Overview selected={selected} onSelect={setSelectedId} />}{view === "method" && <Method />}{view === "evidence" && <Evidence selected={selected} />}</main>; }
