"use client";

import { useMemo, useState } from "react";
import { finalPortfolioImpact, maximumStressedDrawdown, stressImpact } from "@/lib/presentation-metrics";
import { defaultVerifiedRun, verifiedRuns, type VerifiedRun, type VerifiedRunId } from "@/lib/verified-runs";
import { replayViews, type ReplayView } from "@/lib/replay-navigation";
import { runContext } from "@/lib/run-context";
import type { ChartPoint, Evaluation, RunTelemetry } from "@/lib/telemetry";

type WorkspaceTab = ReplayView | "risk" | "events" | "provenance";

const pct = new Intl.NumberFormat("en-AU", { style: "percent", minimumFractionDigits: 2, maximumFractionDigits: 2 });
const dateFormat = new Intl.DateTimeFormat("en-AU", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" });
const title = (value: string) => value.split("_").map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`).join(" ");
const displayDate = (value: string) => dateFormat.format(new Date(`${value}T00:00:00Z`));
const displayOrigin = (value: string) => value.replace("AI-selected", "AI Selected");
const displayStatus = (value: string | null | undefined) => value ? title(value) : "—";
const verdictFor = (run: RunTelemetry, evaluation: Evaluation) => run.defenderVerdicts.find((item) => item.scenarioId === evaluation.result.scenarioId);
const stressComponent = (evaluation: Evaluation) => evaluation.scenario.components.find((item) => item.date !== null || item.startDate !== null);

function line(points: readonly ChartPoint[], value: (point: ChartPoint) => number, min: number, max: number): string {
  return points.map((point, index) => `${index ? "L" : "M"}${index / Math.max(1, points.length - 1) * 1000},${400 - ((value(point) - min) / Math.max(.0001, max - min)) * 400}`).join(" ");
}

function PortfolioChart({ evaluation, mode }: { evaluation: Evaluation; mode: "equity" | "drawdown" }) {
  const [active, setActive] = useState<number | null>(null); const points = evaluation.chartPoints;
  const component = stressComponent(evaluation); const stressDate = component?.date ?? component?.startDate; const stressEnd = component?.endDate;
  const stressIndex = Math.max(0, points.findIndex((point) => point.date === stressDate));
  const values = mode === "equity" ? points.flatMap((point) => [point.baselineEquity, point.stressedEquity]) : points.map((point) => -point.stressedDrawdown);
  const min = mode === "equity" ? Math.min(...values) * .985 : Math.min(...values) * 1.07; const max = mode === "equity" ? Math.max(...values) * 1.01 : 0;
  const focused = active === null ? null : points[active]; const x = stressIndex / Math.max(1, points.length - 1) * 1000; const endIndex = stressEnd ? points.findIndex((point) => point.date === stressEnd) : -1; const endX = endIndex >= 0 ? endIndex / Math.max(1, points.length - 1) * 1000 : x;
  const select = (clientX: number, bounds: DOMRect) => setActive(Math.round(Math.max(0, Math.min(1, (clientX - bounds.left) / bounds.width)) * (points.length - 1)));
  return <div className="sim-chart-wrap"><svg viewBox="0 0 1000 490" role="img" tabIndex={0} aria-label={mode === "equity" ? "Portfolio equity chart" : "Portfolio drawdown chart"} onPointerMove={(event) => select(event.clientX, event.currentTarget.getBoundingClientRect())} onPointerLeave={() => setActive(null)} onKeyDown={(event) => { if (event.key === "ArrowRight") { event.preventDefault(); setActive(Math.min(points.length - 1, (active ?? 0) + 1)); } if (event.key === "ArrowLeft") { event.preventDefault(); setActive(Math.max(0, (active ?? points.length - 1) - 1)); } }}>
    {[0,.2,.4,.6,.8,1].map((ratio) => <g key={ratio}><line className="sim-grid" x1="0" x2="1000" y1={40 + ratio * 400} y2={40 + ratio * 400}/><text className="sim-axis" x="-7" y={44 + ratio * 400} textAnchor="end">{mode === "equity" ? (max - (max-min)*ratio).toFixed(2) : pct.format(max-(max-min)*ratio)}</text></g>)}
    {mode === "equity" ? <><path className="sim-line baseline" d={line(points, (point) => point.baselineEquity, min, max)} transform="translate(0 40)"/><path className="sim-line stressed" d={line(points, (point) => point.stressedEquity, min, max)} transform="translate(0 40)"/></> : <><path className="loss-fill" d={`${line(points, (point) => -point.stressedDrawdown, min, max)} L1000,400 L0,400 Z`} transform="translate(0 40)"/><path className="sim-line drawdown" d={line(points, (point) => -point.stressedDrawdown, min, max)} transform="translate(0 40)"/></>}
    {stressEnd && endIndex >= 0 ? <g className="stress-window"><rect x={x} y="40" width={Math.max(2,endX-x)} height="400"/><line x1={x} x2={x} y1="30" y2="444"/><line x1={endX} x2={endX} y1="40" y2="444"/><text x={Math.min(x+7,810)} y="23">Stress Window · {displayDate(stressDate!)} – {displayDate(stressEnd)}</text></g> : <g className="stress-marker"><line x1={x} x2={x} y1="30" y2="444"/><text x={Math.min(x + 7, 870)} y="23">Stress Applied · {stressDate ? displayDate(stressDate) : "—"}</text></g>}
    {focused && <g className="chart-focus"><line x1={active! / Math.max(1, points.length-1)*1000} x2={active! / Math.max(1, points.length-1)*1000} y1="40" y2="440"/><line x1="0" x2="1000" y1={40 + 400 - ((mode === "equity" ? focused.stressedEquity : -focused.stressedDrawdown)-min)/Math.max(.0001,max-min)*400} y2={40 + 400 - ((mode === "equity" ? focused.stressedEquity : -focused.stressedDrawdown)-min)/Math.max(.0001,max-min)*400}/>{mode === "equity" && <><circle cx={active! / Math.max(1, points.length-1)*1000} cy={40 + 400 - (focused.baselineEquity-min)/Math.max(.0001,max-min)*400} r="3" className="focus-baseline"/><circle cx={active! / Math.max(1, points.length-1)*1000} cy={40 + 400 - (focused.stressedEquity-min)/Math.max(.0001,max-min)*400} r="3" className="focus-stressed"/></>}</g>}
    <text className="sim-axis" x="0" y="487">{displayDate(points[0]?.date ?? "2024-01-02")}</text><text className="sim-axis" x="1000" y="487" textAnchor="end">{displayDate(points.at(-1)?.date ?? "2024-04-23")}</text>
  </svg>{focused && <aside className="sim-tooltip" aria-live="polite"><b>{displayDate(focused.date)}</b><span>Baseline <strong>{focused.baselineEquity.toFixed(4)}</strong></span><span>Stressed <strong>{focused.stressedEquity.toFixed(4)}</strong></span><span>Difference <strong>{pct.format(focused.stressedEquity / focused.baselineEquity - 1)}</strong></span><span>Drawdown <strong>{pct.format(focused.stressedDrawdown)}</strong></span></aside>}</div>;
}

function Help({ open, onClose }: { open: boolean; onClose: () => void }) { if (!open) return null; return <div className="help-layer" role="dialog" aria-modal="true" aria-label="About This Simulation"><section><button aria-label="Close About This Simulation" onClick={onClose}>×</button><h2>About This Simulation</h2><p>This simulator stress-tests a systematic 60/40 portfolio. A model can select from prevalidated market stresses; deterministic Python calculates outcomes; an independent defender replay checks reproducibility.</p><p>Public scenarios are precomputed verified evidence only. There is no live trading, investment advice, public Python backend, or live model call.</p></section></div>; }

function Sidebar({ selected, setSelected }: { selected: VerifiedRun; setSelected: (id: VerifiedRunId) => void }) { const index = verifiedRuns.findIndex((item) => item.id === selected.id); const evaluation = selected.evaluation; const replay = verdictFor(selected.run, evaluation); const change = (step: number) => setSelected(verifiedRuns[(index + step + verifiedRuns.length) % verifiedRuns.length]!.id); return <aside className="sim-sidebar"><p className="panel-label">Stress Lab</p><label htmlFor="verified-scenario">Scenario</label><select id="verified-scenario" value={selected.id} onChange={(event) => setSelected(event.target.value as VerifiedRunId)}>{verifiedRuns.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select><small>Precomputed Replay</small><dl><div><dt>Attack Family</dt><dd>{title(selected.family)}</dd></div><div><dt>Origin</dt><dd>{displayOrigin(selected.origin)}</dd></div><div><dt>Verification</dt><dd className="good">{displayStatus(replay?.verdict ?? selected.run.verificationVerdict)}</dd></div><div><dt>Status</dt><dd>{displayStatus(evaluation.result.status)}</dd></div></dl><div className="side-actions"><button onClick={() => change(-1)}>← Previous</button><button onClick={() => change(1)}>Next →</button></div></aside>; }

function Inspector({ selected }: { selected: VerifiedRun }) { const { evaluation, run } = selected; const component = evaluation.scenario.components[0]; const replay = verdictFor(run, evaluation); const impact = stressImpact(evaluation); const drawdown = maximumStressedDrawdown(evaluation); const date = component?.date ?? component?.startDate; return <aside className="sim-inspector"><p className="panel-label">Selected Stress</p><h2>{selected.displayName}</h2><time>{date ? displayDate(date) : "Full Evaluation Window"}</time><section><p>Parameters</p>{component?.shocks ? <dl><div><dt>SPY</dt><dd>{pct.format(component.shocks.SPY ?? 0)}</dd></div><div><dt>TLT</dt><dd>{pct.format(component.shocks.TLT ?? 0)}</dd></div></dl> : <dl><div><dt>{component?.volatilityMultiplier !== null ? "Volatility Multiplier" : "Target Correlation"}</dt><dd>{component?.volatilityMultiplier !== null ? `${component?.volatilityMultiplier ?? "—"}×` : component?.targetCorrelation ?? "—"}</dd></div><div><dt>Stress Window</dt><dd>{component?.startDate && component.endDate ? `${displayDate(component.startDate)} – ${displayDate(component.endDate)}` : "—"}</dd></div></dl>}</section><section><p>Portfolio Effect</p><dl><div><dt>Immediate Impact <abbr title="Difference between stressed and baseline portfolio value at the canonical stress application point.">i</abbr></dt><dd className="loss">{pct.format(impact)}</dd></div><div><dt>Max Drawdown <abbr title="Largest decline from the stressed portfolio's prior peak.">i</abbr></dt><dd>{pct.format(drawdown)}</dd></div><div><dt>Risk Events <abbr title="Number of recorded risk-limit breach events in verified telemetry.">i</abbr></dt><dd>{evaluation.result.breachCount}</dd></div></dl></section><section><p>Verification</p><dl><div><dt>Verdict</dt><dd className="good">{displayStatus(replay?.verdict)} ✓</dd></div><div><dt>Replay Delta <abbr title="Largest numerical difference between the original deterministic evaluation and defender replay.">i</abbr></dt><dd>{replay?.maxMetricDelta.toFixed(1) ?? "—"}</dd></div></dl></section><footer>{displayOrigin(selected.origin)}</footer></aside>; }

function OverviewTab({ selected }: { selected: VerifiedRun }) { const context = runContext(selected.id, selected.run.configSha256); const last = selected.evaluation.chartPoints.at(-1); return <section className="analysis-table"><h2>Simulation Overview</h2><table><tbody><tr><th>Strategy</th><td>{context.strategy}</td><th>Period</th><td>{context.period}</td></tr><tr><th>Rebalancing</th><td>{context.rebalancing}</td><th>Final Baseline</th><td>{last?.baselineEquity.toFixed(4)}</td></tr><tr><th>Final Stressed</th><td>{last?.stressedEquity.toFixed(4)}</td><th>Final Impact</th><td className="loss">{pct.format(finalPortfolioImpact(selected.evaluation))}</td></tr></tbody></table></section>; }
function AnalysisTabs({ selected, active, setActive }: { selected: VerifiedRun; active: WorkspaceTab; setActive: (view: WorkspaceTab) => void }) { const { run, evaluation } = selected; const replay = verdictFor(run, evaluation); return <section className="bottom-workspace"><nav aria-label="Simulation analysis">{replayViews.map((item) => <button key={item.id} className={active === item.id ? "active" : ""} onClick={() => setActive(item.id)}>{item.id === "method" ? "Verification" : item.label}</button>)}<button className={active === "risk" ? "active" : ""} onClick={() => setActive("risk")}>Risk</button><button className={active === "events" ? "active" : ""} onClick={() => setActive("events")}>Event Log</button><button className={active === "provenance" ? "active" : ""} onClick={() => setActive("provenance")}>Provenance</button></nav>{active === "overview" && <OverviewTab selected={selected}/>} {active === "risk" && <section className="analysis-table"><h2>Risk</h2><table><tbody><tr><th>Recorded Risk Events</th><td>{evaluation.result.breachCount}</td><th>Maximum Normalized Excess</th><td>{evaluation.result.maximumNormalizedExcess}</td></tr></tbody></table></section>} {active === "method" && <section className="verification-chain"><div>Initial Deterministic Evaluation</div><span>↓</span><div>Independent Defender Replay</div><span>↓</span><div className="good">{replay?.verdict ?? "—"} · Δ {replay?.maxMetricDelta.toFixed(1) ?? "—"}</div></section>} {active === "events" && <section className="event-log"><h2>Canonical Event Log</h2><table><thead><tr><th>Seq</th><th>Phase</th><th>Event</th><th>Scenario</th></tr></thead><tbody>{run.events.map((event) => <tr key={event.sequence}><td>{String(event.sequence).padStart(2,"0")}</td><td>{event.roundNumber ? `Round ${event.roundNumber}` : "Run"}</td><td>{title(event.eventType)}</td><td><code>{event.scenarioId ?? "—"}</code></td></tr>)}</tbody></table></section>} {active === "provenance" && <section className="analysis-table"><h2>Provenance</h2><table><tbody><tr><th>Data SHA256</th><td><code>{run.dataSha256}</code></td><th>Config SHA256</th><td><code>{run.configSha256}</code></td></tr><tr><th>Fixture</th><td><code>{selected.sourceArtifact}</code></td><th>Provider / Model</th><td>{run.provider} / {run.modelIdentifier ?? "deterministic"}</td></tr><tr><th>Scenario ID</th><td><code>{evaluation.result.scenarioId}</code></td><th>Origin</th><td>{selected.origin}</td></tr></tbody></table></section>}</section>; }

export function ReplayDashboard() { const [selectedId, setSelectedId] = useState<VerifiedRunId>(defaultVerifiedRun.id); const [chartMode, setChartMode] = useState<"equity" | "drawdown">("equity"); const [tab, setTab] = useState<WorkspaceTab>("overview"); const [help, setHelp] = useState(false); const selected = useMemo(() => verifiedRuns.find((item) => item.id === selectedId) ?? defaultVerifiedRun, [selectedId]); return <main className="simulator"><header className="appbar"><strong>Red-Team Lab</strong><span>60/40 SPY–TLT</span><span>Monthly Rebalance</span><div/><b>● Verified</b><button onClick={() => setHelp(true)}>About This Simulation</button><a href="https://github.com/cx07-oss/strategy-redteam-lab" target="_blank" rel="noreferrer">View Source ↗</a></header><section className="sim-workspace"><Sidebar selected={selected} setSelected={setSelectedId}/><section className="chart-workspace"><header><div><h1>Portfolio Equity</h1><p>{chartMode === "equity" ? "Normalized Value · 1.00 = Starting Portfolio Value" : "Drawdown = Decline From Previous Portfolio Peak"}</p></div><div className="chart-switch"><button className={chartMode === "equity" ? "active" : ""} onClick={() => setChartMode("equity")}>Equity</button><button className={chartMode === "drawdown" ? "active" : ""} onClick={() => setChartMode("drawdown")}>Drawdown</button></div></header><div className="chart-keys"><i className="key-baseline"/>Baseline <i className="key-stressed"/>Stressed <i className="key-marker"/>Stress Window</div><PortfolioChart evaluation={selected.evaluation} mode={chartMode}/></section><Inspector selected={selected}/></section><AnalysisTabs selected={selected} active={tab} setActive={setTab}/><Help open={help} onClose={() => setHelp(false)}/></main>; }
